export const car = [
  {
    id: 301,
    brand: "Toyota",
    model: "Fortuner",
    year: "(2024)",
    price: "42 Lakh",
    currency: "INR",
    mileage: 8500,
    fuelType: "Diesel",
    transmission: "Automatic",
    bodyType: "SUV",
    color: "White",
    engine: "2.8L Diesel",
    horsepower: 204,
    seats: 7,
    doors: 5,
    location: "Chandigarh",
    state: "Chandigarh",
    country: "India",
    rating: 4.8,
    isAvailable: true,
    isFeatured: true,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcStkRzLj3f24NYQDPAHL0KcbMKlONJqqhXZKHCNjjw0Bw&s=10"
  },

  {
    id: 302,
    brand: "BMW",
    model: "X5",
    year: "(2024)",
    price: "95 Lakh",
    currency: "INR",
    mileage: 6200,
    fuelType: "Petrol",
    transmission: "Automatic",
    bodyType: "SUV",
    color: "Blue",
    engine: "3.0L Turbo",
    horsepower: 335,
    seats: 5,
    doors: 5,
    location: "Mumbai",
    state: "Maharashtra",
    country: "India",
    rating: 4.9,
    isAvailable: true,
    isFeatured: true,
    image:
      "https://imgd-ct.aeplcdn.com/664x415/n/3te3bbb_1676645.png?q=80"
  },

  {
    id: 303,
    brand: "Mercedes-Benz",
    model: "GLC",
    year: "(2024)",
    price: "76 Lakh",
    currency: "INR",
    mileage: 7100,
    fuelType: "Petrol",
    transmission: "Automatic",
    bodyType: "SUV",
    color: "Silver",
    engine: "2.0L Turbo",
    horsepower: 255,
    seats: 5,
    doors: 5,
    location: "Delhi",
    state: "Delhi",
    country: "India",
    rating: 4.8,
    isAvailable: true,
    isFeatured: true,
    image:
      "https://www.motortrend.com/uploads/2024/01/001-2024-Mercedes-Benz-GLC-300-front-view.jpg?format=webp&q=75&w=1200"
  },

  {
    id: 304,
    brand: "Audi",
    model: "Q7",
    year: "(2024)",
    price: "88 Lakh",
    currency: "INR",
    mileage: 5800,
    fuelType: "Petrol",
    transmission: "Automatic",
    bodyType: "SUV",
    color: "Blue",
    engine: "3.0L TFSI",
    horsepower: 335,
    seats: 7,
    doors: 5,
    location: "Bangalore",
    state: "Karnataka",
    country: "India",
    rating: 4.9,
    isAvailable: true,
    isFeatured: true,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSmxnlbgprMCwV53ArAqfolkuEy6IrbnOnBRLFexWH_sg&s=10"
  },

  {
    id: 305,
    brand: "Hyundai",
    model: "Tucson",
    year: "(2024)",
    price: "19 Lakh",
    currency: "INR",
    mileage: 6900,
    fuelType: "Diesel",
    transmission: "Automatic",
    bodyType: "SUV",
    color: "White",
    engine: "2.0L Diesel",
    horsepower: 186,
    seats: 5,
    doors: 5,
    location: "Delhi",
    state: "Delhi",
    country: "India",
    rating: 4.6,
    isAvailable: true,
    isFeatured: false,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT61Jb2aHx_66ZBEoGeYQhw0f-zhvloAGVH-9lkprawRA&s=10"
  },

  {
    id: 306,
    brand: "Kia",
    model: "Carnival",
    year: "(2024)",
    price: "35 Lakh",
    currency: "INR",
    mileage: 7600,
    fuelType: "Diesel",
    transmission: "Automatic",
    bodyType: "MPV",
    color: "Silver",
    engine: "2.2L Diesel",
    horsepower: 197,
    seats: 7,
    doors: 5,
    location: "Pune",
    state: "Maharashtra",
    country: "India",
    rating: 4.7,
    isAvailable: true,
    isFeatured: true,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRQ2FxK1P5xPu7Hb_6RY7ZG2GhUXN008n7JeJBO7nO9sw&s=10"
  },

  {
    id: 307,
    brand: "Tata",
    model: "Nexon",
    year: "(2024)",
    price: "15 Lakh",
    currency: "INR",
    mileage: 5400,
    fuelType: "Petrol",
    transmission: "Automatic",
    bodyType: "SUV",
    color: "Blue",
    engine: "1.2L Turbo",
    horsepower: 118,
    seats: 5,
    doors: 5,
    location: "Mohali",
    state: "Punjab",
    country: "India",
    rating: 4.5,
    isAvailable: true,
    isFeatured: false,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTLe7EYGVgV5qo3hjEVounGodKEI56g4ez6LGQlVGJTVw&s=10"
  },

  {
    id: 308,
    brand: "Mahindra",
    model: "XUV700",
    year: "(2024)",
    price: "24.5 Lakh",
    currency: "INR",
    mileage: 8200,
    fuelType: "Diesel",
    transmission: "Automatic",
    bodyType: "SUV",
    color: "Black",
    engine: "2.2L Diesel",
    horsepower: 182,
    seats: 7,
    doors: 5,
    location: "Mohali",
    state: "Punjab",
    country: "India",
    rating: 4.7,
    isAvailable: true,
    isFeatured: true,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSKIQbNJaoTF6m8eweINbqISf5cp5VrGBf58j7T8TjQiA&s=10"
  },

  {
    id: 309,
    brand: "Maruti Suzuki",
    model: "Grand Vitara",
    year: "(2024)",
    price: "8 Lakh",
    currency: "INR",
    mileage: 6200,
    fuelType: "Petrol",
    transmission: "Automatic",
    bodyType: "SUV",
    color: "Red",
    engine: "1.5L",
    horsepower: 103,
    seats: 5,
    doors: 5,
    location: "Jaipur",
    state: "Rajasthan",
    country: "India",
    rating: 4.5,
    isAvailable: true,
    isFeatured: false,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQtbMwzq2LQkbrG5sTuZwvQy_vsbbrYIxqMuUPK0pBXFg&s=10"
  },

  {
    id: 310,
    brand: "Toyota",
    model: "Innova Hycross",
    year: "(2024)",
    price: "17 Lakh",
    currency: "INR",
    mileage: 7300,
    fuelType: "Hybrid",
    transmission: "Automatic",
    bodyType: "MPV",
    color: "White",
    engine: "2.0L Hybrid",
    horsepower: 184,
    seats: 7,
    doors: 5,
    location: "Lucknow",
    state: "Uttar Pradesh",
    country: "India",
    rating: 4.8,
    isAvailable: true,
    isFeatured: true,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQJRDcXKfPAlC55PB9Fg34o73ujAt1G3lnesyu4-uheEA&s=10"
  },

  {
    id: 311,
    brand: "MG",
    model: "Hector",
    year: "(2024)",
    price: "22 Lakh",
    currency: "INR",
    mileage: 6700,
    fuelType: "Petrol",
    transmission: "Automatic",
    bodyType: "SUV",
    color: "Black",
    engine: "1.5L Turbo",
    horsepower: 141,
    seats: 5,
    doors: 5,
    location: "Ahmedabad",
    state: "Gujarat",
    country: "India",
    rating: 4.5,
    isAvailable: true,
    isFeatured: false,
    image:
      "https://asset.autocarindia.com/static/models/colors/20251215_102059_2654364c.png?w=640&q=75&fm=auto"
  },

  {
    id: 312,
    brand: "Skoda",
    model: "Slavia",
    year: "(2024)",
    price: "18.5 Lakh",
    currency: "INR",
    mileage: 4900,
    fuelType: "Petrol",
    transmission: "Automatic",
    bodyType: "Sedan",
    color: "White",
    engine: "1.5L TSI",
    horsepower: 148,
    seats: 5,
    doors: 4,
    location: "Chandigarh",
    state: "Chandigarh",
    country: "India",
    rating: 4.6,
    isAvailable: true,
    isFeatured: false,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQLqe1D20_f19G_Ru19KD3-MFFCHWZMrgs4nnBF_-4zMw&s=10"
  },

  {
    id: 313,
    brand: "Volkswagen",
    model: "Virtus",
    year: "(2024)",
    price: "19 Lakh",
    currency: "INR",
    mileage: 5300,
    fuelType: "Petrol",
    transmission: "Automatic",
    bodyType: "Sedan",
    color: "Blue",
    engine: "1.5L TSI",
    horsepower: 148,
    seats: 5,
    doors: 4,
    location: "Delhi",
    state: "Delhi",
    country: "India",
    rating: 4.6,
    isAvailable: true,
    isFeatured: false,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSX2tdvPzJN_JWYa1L1XyKxpKWWWT4iMa-Rrn56-ypSIw&s=10"
  },

  {
    id: 314,
    brand: "Honda",
    model: "Elevate",
    year: "(2024)",
    price: "10 Lakh",
    currency: "INR",
    mileage: 4600,
    fuelType: "Petrol",
    transmission: "CVT",
    bodyType: "SUV",
    color: "White",
    engine: "1.5L",
    horsepower: 119,
    seats: 5,
    doors: 5,
    location: "Bangalore",
    state: "Karnataka",
    country: "India",
    rating: 4.5,
    isAvailable: true,
    isFeatured: false,
    image:
      "https://static.toiimg.com/thumb/msid-103351581,width-1280,height-720,resizemode-4/103351581.jpg"
  },

  {
    id: 315,
    brand: "Jeep",
    model: "Compass",
    year: "(2024)",
    price: "28 Lakh",
    currency: "INR",
    mileage: 7900,
    fuelType: "Diesel",
    transmission: "Automatic",
    bodyType: "SUV",
    color: "White",
    engine: "2.0L Diesel",
    horsepower: 168,
    seats: 5,
    doors: 5,
    location: "Chandigarh",
    state: "Chandigarh",
    country: "India",
    rating: 4.6,
    isAvailable: true,
    isFeatured: true,
    image:
      "https://www.jeep.co.uk/content/dam/jeep/uk/compass-models/jan-25/JEEP-COMPASS-SUMMIT-PHEV-MY25-ALPINE-WHITE-FIGURINE_725x408.png"
  },

  {
    id: 316,
    brand: "Toyota",
    model: "Hilux",
    year: "(2024)",
    price: "30 Lakh",
    currency: "INR",
    mileage: 8800,
    fuelType: "Diesel",
    transmission: "Automatic",
    bodyType: "Pickup",
    color: "Grey",
    engine: "2.8L Diesel",
    horsepower: 201,
    seats: 5,
    doors: 4,
    location: "Chandigarh",
    state: "Chandigarh",
    country: "India",
    rating: 4.7,
    isAvailable: true,
    isFeatured: true,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQyDfrmheDdlIEOqVB6x8CzRMJfuXt34DCFri490SGzDQ&s=10"
  },

  {
    id: 317,
    brand: "Isuzu",
    model: "MU-X",
    year: "(2024)",
    price: "20 Lakh",
    currency: "INR",
    mileage: 9100,
    fuelType: "Diesel",
    transmission: "Automatic",
    bodyType: "SUV",
    color: "Black",
    engine: "3.0L Diesel",
    horsepower: 187,
    seats: 7,
    doors: 5,
    location: "Mumbai",
    state: "Maharashtra",
    country: "India",
    rating: 4.6,
    isAvailable: true,
    isFeatured: false,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRJjaiUsszftbdg4jaeI4Fjr5DoomA8jiJwH_X-MVQsDQ&s=10"
  },

  {
    id: 318,
    brand: "BYD",
    model: "Seal",
    year: "(2024)",
    price: "53 Lakh",
    currency: "INR",
    mileage: 3500,
    fuelType: "Electric",
    transmission: "Automatic",
    bodyType: "Sedan",
    color: "Blue",
    engine: "Dual Motor AWD",
    horsepower: 523,
    seats: 5,
    doors: 4,
    location: "Delhi",
    state: "Delhi",
    country: "India",
    rating: 4.8,
    isAvailable: true,
    isFeatured: true,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ3QUws30oU_u6ShQLl533f1-J_lOWklF0aimuCMkQMKw&s=10"
  },

  {
    id: 319,
    brand: "Lexus",
    model: "RX",
    year: "(2024)",
    price: "98 Lakh",
    currency: "INR",
    mileage: 4200,
    fuelType: "Hybrid",
    transmission: "Automatic",
    bodyType: "SUV",
    color: "Silver",
    engine: "2.4L Turbo Hybrid",
    horsepower: 366,
    seats: 5,
    doors: 5,
    location: "Mumbai",
    state: "Maharashtra",
    country: "India",
    rating: 4.9,
    isAvailable: true,
    isFeatured: true,
    image:
      "https://stimg.cardekho.com/images/carexteriorimages/630x420/Lexus/RX/11360/1769081565510/front-left-side-47.jpg?tr=w-664"
  },

  {
    id: 320,
    brand: "Nissan",
    model: "X-Trail",
    year: "(2024)",
    price: "49 Lakh",
    currency: "INR",
    mileage: 5100,
    fuelType: "Petrol",
    transmission: "CVT",
    bodyType: "SUV",
    color: "Grey",
    engine: "1.5L Turbo",
    horsepower: 163,
    seats: 7,
    doors: 5,
    location: "Pune",
    state: "Maharashtra",
    country: "India",
    rating: 4.5,
    isAvailable: true,
    isFeatured: false,
    image:
      "https://stimg.cardekho.com/images/carexteriorimages/930x620/Nissan/X-Trail/3372/1764934756316/front-left-side-47.jpg"
  }
];